### ISSUE TITLE
Initial site setup

### ISSUE THREAD

**Issue by garethrees** [mysociety/wob-knop-theme#1]
## [Set up and get to know the site](http://alaveteli.org/docs/getting_started/#step-one-get-a-working-uncustomised-version-running)
- [x] Get an uncustomised version of the site running (mySociety).
- [x] Give mySociety a list of email addresses to be used for support mail - so when someone using the site needs help and mails `team@[sitename]`, who should receive the emails? (partner) 
- [x] Create accounts on the site for partner team (partner)
- [x] Set up admin accounts for the partner team (mySociety)
- [x] Add email override for authorities so that all emails go to `team@` address (mySociety)
- [ ] Play with the site to see how it works as a user, as an [administrator](http://alaveteli.org/docs/running/admin_manual/), and as a public authority (partner)
- [x] Add some authorities to the site using the admin interface (partner)

## [Gather public authority information](http://alaveteli.org/docs/getting_started/#step-two-start-to-gather-data-about-public-authorities)

- [x] Gather authority email addresses (partner) - [format template](https://docs.google.com/spreadsheets/d/13EIEydU9tufH53VMNHb_oU7vBBpR_QVk6K0s6jpW5Dw/edit?hl=en_US#gid=0) and [format help](http://alaveteli.org/docs/running/admin_manual/#creating-changing-and-uploading-public-authority-data).
- [x] Import authorities (https://github.com/mysociety/wob-knop-theme/issues/11)

### Provide your theme colours

- [x] Create a logo for the site (partner) (https://github.com/mysociety/wob-knop-theme/issues/15)
- [x] Choose photo for homepage banner and send to mySociety (partner) ([link](https://groups.google.com/a/mysociety.org/d/msg/alaveteli/1OvqHzjRezc/ncOWxDxiDwAJ))
- [x] Choose a primary colour for the site (banner and other UI elements) (partner) `#ffe384`

Take a look at our [example theme](https://github.com/mysociety/alaveteli/wiki/Initial-theme-customisation) to get an idea of how your Alaveteli will look.

### More customization
- [x] Set up social media accounts for the site, tell mySociety what they are (partner)
- [x] Configure social media accounts for the site (mySociety)
- [x] Buy domain name (partner) `www.wob-knop.nl` (`wobknop.nl` as a redirect`)
- [x] Configure DNS (#6)
- [x] Configure reCAPTCHA (#8)
- [x] Tell mySociety how many days should pass before a request is classified as 'late' [(documentation)](http://alaveteli.org/docs/customising/config/#reply_late_after_days) (partner) `28 days / 56 days`
- [ ] Set up a google analytics account and share the information with mySociety (partner)
- [ ] Configure the analytics account on the site and in ProjectDB (mySociety)
- [x] Acquire and install an SSL certificate for the site (mySociety) (#7)
- [ ] Add public holidays to the site using the admin interface (partner)
- [x] Send [data sharing agreement](https://wiki.mysociety.org/wiki/General_Data_Protection_Regulation_(GDPR)) to partner (mySociety) (https://github.com/mysociety/wob-knop-theme/issues/16)

## [Translate the site]( http://alaveteli.org/docs/getting_started/#step-four-translate-everything)
- [x] Send a list of letters in in alphabetical order for each site language (except English) for the "Beginning with" list on http://demo.alaveteli.org/body/list/all (partner) `A-Z`
- [x] Translate the text in Transifex, or see if an existing translation can be used (partner)
- [x] Write the help pages for the site (partner). Common help pages are [here](http://alaveteli.org/docs/customising/themes/#customising-the-help-pages), but others can be added and some omitted. (https://github.com/mysociety/wob-knop-theme/issues/10)

## Launch the site 
- [ ] Populate the site with some requests pre-launch with help from own contacts (partner)
- [x] Remove test data (mySociety)
- [ ] Remove email override for authorities (mySociety)
- [ ] Remove `cron-alaveteli` from `team@` email

## [Market the site](http://alaveteli.org/docs/getting_started/#step-six-market-the-website)
- [x] Think about launch event (partner) 
- [ ] Apply for an adwords grant (partner)
- [ ] Consider press releases to relevant organisations (partner)
- [ ] Think about audience and how to engage them in the platform before and after launch - for example; workshops with NGOs about how the site can help them get info for their work etc (partner)
- [ ] Watch for interesting or high traffic requests/responses and consider how to market them (partner)

## [Maintain the site](http://alaveteli.org/docs/getting_started/#step-seven-maintain-the-website)

**Comment by garethrees** [comment]
Some relevant threads:

* https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/uYZeJXydHFs
* https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/1OvqHzjRezc
* https://groups.google.com/a/mysociety.org/d/msg/alaveteli/NiffiTyaAhk/IqBZ-WRyDwAJ

Will try to extract the relevant information from these at some point.

**Comment by garethrees** [comment]
@JenMysoc If they're looking for things to do, next step would be looking at the help pages and making sure they're applicable.

**Comment by garethrees** [comment]
`SITE_NAME: De Wob-knop`

**Comment by garethrees** [comment]
Another email about help pages: https://groups.google.com/a/mysociety.org/d/msg/alaveteli/N483RRB_xAM/373iK6SKBAAJ

**Comment by garethrees** [comment]
Calendar days

**Comment by JenMysoc** [comment]
https://docs.google.com/document/d/15gCD933KGSGyo6rvFBzYg0jINsi8cGmfGkl1l_equkw/edit?ts=5dd25b3e#heading=h.5vkioi1jsn5i is the pro help page

**Comment by JenMysoc** [comment]
[Wob-knop huisstijl.pdf](https://github.com/mysociety/wob-knop-theme/files/3857712/Wob-knop.huisstijl.pdf)

Logo PDF
